### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200e' in position 196: ordinal not in range(128)

### ISSUE THREAD

**Issue by lwiecek** [adamchainz/logentries-cli#7]
I'm running this command:

`logentries application app -s 'yesterday' | grep /api/app/ > ratelimiting_api.log`

stderr looks like so:

```
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/logentries", line 204, in <module>
    sys.exit(main(**kwargs))
  File "/usr/local/bin/logentries", line 124, in main
    print(line.decode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200e' in position 196: ordinal not in range(128)
```

**Comment by adamchainz** [comment]
Unmaintaining.
